### ISSUE TITLE
Koordinierungs-Treffen 01

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#1]
@SECH-Tag-EEXCESS-Browser/team-sech 
Wir brauchen einen Termin, wann wir uns einmal in der Woche treffen können um anstehende Koordinierungs Aufgaben zu besprechen. Dies sollte pro Woche je nach anstehendem Gesprächsbedarf etwa 30-60 Minuten dauern.
Mein Vorschlag wäre Mittwoch 12:30 oder Donnerstag 12:30. (Alternativ Dienstag 10:45)
Bitte kommentiert, ob ihr mit **einem** der Termine einverstanden seid und wenn ja mit **welchem**, oder, wenn nicht, macht bitte Gegenvorschläge.
Diese kurzen Treffen sind gedacht als Abstimmung mit Prof. Stöhr, der auch anwesend sein wird.
Die restliche Zeit der pro Woche aufzuwendenden 6h kann dann in den Teams besprochen werden.

Für das erste Treffen:
- Wir besprechen die erarbeitete Struktur
- Wir bilden darauf gründend neue Teams
- Wir entwerfen Labels
- Wir besprechen Regeln für die Dokumentation
- Wir besprechen Regeln für das Wiki
- Wir besprechen Regeln für das Projekt

Ich würde als Projektmanagementstil gerne Kanban einführen, das kann ich gerne kurz erklären, bitte informiert doch auch vorab schon.
https://de.wikipedia.org/wiki/Kanban_%28Softwareentwicklung%29
Dazu würde ich gerne ein Tool einführen, das als Plugin in GitHub läuft.
Es heißt ZenHub und läuft als Plugin in Firefox und Chrome
Bitte schaut es Euch an:
https://www.zenhub.io/

Ich mache gerne nach Ostern einen Kanban CrashKurs mit Euch, das hilft uns für das Projekt.

**Comment by bmairhoermann** [comment]
Ich bin mit allen Terminen einverstanden.

**Comment by GvRecum** [comment]
Bitte schreibt dazu mit welchem, damit es eine auswertbare Abstimmung wird. Danke.

**Comment by pstoehr** [comment]
Bei mir klappen wohl
    Mittwoch und Donnerstag 12:30 
in der Regel auch!

**Comment by bmairhoermann** [comment]
Donnerstag

**Comment by pwinterh** [comment]
Donnerstag

**Comment by lmoedl** [comment]
Donnerstag

**Comment by Anetsch** [comment]
Donnerstag

**Comment by apoehlmann** [comment]
Donnerstag ist ok

**Comment by GvRecum** [comment]
Also, Donnerstags 12:30 Treffen! (erstes Treffen **HEUTE** 17.03.2016 )
Laut Raumsuche ist das **Mobile Computing Labor** frei, also treffen wir uns immer dort.
Bitte noch @berol2 und @drui Bescheid geben!
Wenn ich das richtig verstanden habe nehmen @tpohrer und @pbuettner90 dieses Semester **nicht** an der Vorlesung teil?

**Comment by drui** [comment]
Donnerstag wenns sein muss ok.
Aber gegen irgendwelche Browserplugins.

Und heut schaff ichs nicht mehr.

**Comment by ghost** [comment]
Donnerstag klingt gut.
