### ISSUE TITLE
UI Konstruktion Korrektur lesen

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#116]
Bitte  den [UI](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/konstr_UI.tex) Teil der Konstruktion der [Dokumentation](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/Dokumentation.pdf) Korrektur lesen.

Sind die Bilder jetzt an der gewünschten Stelle?
Ist inhaltlich alles korrekt?
Seid Ihr einverstanden mit meinen Änderungen?

Bitte die geänderten **[Dokumentationskonventionen](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/wiki/Dokumentationskonventionen)** beachten.

**Comment by bmairhoermann** [comment]
Alles gut. Done.

**Comment by GvRecum** [comment]
Danke
