### ISSUE TITLE
Lesezeichen überarbeiten

### ISSUE THREAD

**Issue by bmairhoermann** [SECH-Tag-EEXCESS-Browser/SeCH#12]
Die Lesezeichen werde nicht mehr in einem eigenen View angezeigt, sonder am linken Rand des Browsers.

Im Zuge dessen wird eine Tabelle eingefügt die vom Benutzer ein/aus geblendet werden kann.

**Comment by bmairhoermann** [comment]
Done

**Comment by GvRecum** [comment]
Thx.
