### ISSUE TITLE
Regex überprüfen/anpassen

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#21]
Regex an die Neue Struktur anpassen.

**Comment by GvRecum** [comment]
"isMainTopic" im SearchManager entfernen, kommt erst in der QuerryBuild. -> #19
absprechen mit @apoehlmann

**Comment by apoehlmann** [comment]
Beim "type"-Attribute muss der SearchManager auf Groß- und Kleinschreibung achten und bei Bedarf ausbessern

**Comment by bmairhoermann** [comment]
Die Sache mit dem "type" lässt sich lösen.
Wie darf ich das mit der maintopic verstehen?

**Comment by GvRecum** [comment]
"isMainTopic" wird erst "unten" in der Querry Builder gesetzt.

**Comment by bmairhoermann** [comment]
isMainTopic wird nun im SearchManager nicht mehr gesetzt, stattdessen ist das Attribut mit dem Wert nil übergeben.

Nach Besprechung mit Herrn Stöhr muss das case-sensitive nicht in den SearchManager.
