### ISSUE TITLE
neue Webseite anlegen

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#23]

**Comment by pstoehr** [comment]
@GvRecum 
Ist dass nicht ein Duplikat von #25?

**Comment by GvRecum** [comment]
Dieses hier (#23) ist das Issue, #25  ist das dazugehörige Epic, also das "Überthema".

**Comment by GvRecum** [comment]
Ist das noch gewünscht/aktuell/von Nöten,?
Da ja schon eine neue Seite für Köln erstellt wurde.
