### ISSUE TITLE
Tap auf Link führt zu Absturz

### ISSUE THREAD

**Issue by bmairhoermann** [SECH-Tag-EEXCESS-Browser/SeCH#28]
Leicht zu reproduzieren. Gehe auf beliebige Seite und tippe auf einen Link:

<img width="759" alt="bildschirmfoto 2016-04-14 um 14 00 05" src="https://cloud.githubusercontent.com/assets/11869474/14527387/ce769614-0249-11e6-9819-f46309f0cf4a.png">

Folgender Fehler mit Absturz tritt auf:
<img width="1680" alt="bildschirmfoto 2016-04-14 um 13 53 52" src="https://cloud.githubusercontent.com/assets/11869474/14527390/dd78e144-0249-11e6-9870-3669050d6833.png">

**Comment by GvRecum** [comment]
Neue Issues bitte in "New Issues" belassen!
Bitte Personen erwähnen mit einer Mention, also z.B. @lmoedl 
assigned wird erst später, wenn sich jemand das aus "ToDo" holt.
siehe [Issueskonventionen](../wiki/Issueskonventionen)

**Comment by bmairhoermann** [comment]
Alles klar!
@lmoedl 
@apoehlmann 
@drui

**Comment by bmairhoermann** [comment]
fixed by lothar
