### ISSUE TITLE
Fehler beim Aufbau der EEXCESS-Query Objekte bei der Cologne-Site

### ISSUE THREAD

**Issue by pstoehr** [SECH-Tag-EEXCESS-Browser/SeCH#29]
Es sieht so aus, als ob der <search-head> Eintrag nicht korrekt erkannt wird.

Auszug aus der Liste der erzeugten Queries:
1. Eintrag:
   tags    [String : Browser.Tag]  3 key/value pairs  
   [0](key: String, value: Browser.Tag)  
   key String  "link"  
   value   Browser.Tag 0x00007f935b42bcb0
   topic   String  "North Rhine-Westphalia"  
   type    String  "misc"  
   [1](key: String, value: Browser.Tag)  
   key String  "section"  
   value   Browser.Tag 0x00007f9359da7430
   topic   String  "Rhine Metropole"  
   type    String  "misc"  
   [2](key: String, value: Browser.Tag)  
   key String  "head"  
   value   Browser.Tag 0x00007f935b47c8e0
   topic   String  ""  
   type    String  ""  
   Hier fehlt bei "Head" der Eintrag "Cologne".

Dasselbe passiert übrigens bei der Home-Page. Auch hier ist der Head-Wert leer ...

**Comment by bmairhoermann** [comment]
Das Auslesen des HTML-Heads durch Javascript war fehlerhaft.
Gefixt.
