### ISSUE TITLE
Leere Query-Results

### ISSUE THREAD

**Issue by pstoehr** [SECH-Tag-EEXCESS-Browser/SeCH#30]
Die erste SeARCH-Anfrage in der cologne-Website ist immer leer :-(

Eine Abfrage mit dem OS X Query-Tools für 
    North Rhine-Westphalia (MainTopic)
    Rhine Metropole
liefert zumindest für Mendeley immer zuverlässig ein Ergebnis. 
Ist da das Ranking für verantwortlich?

**Comment by lmoedl** [comment]
Ab und zu kommt es vor, dass von Passau keine Ergebnisse zu den o.g. Tags findet. Dann wird aber eine entsprechende "Fehlerseite" angezeigt. Sollten allerdings Antworten gefunden werden und beim draufklicken auf einen Sech-Tag bleibt die Seite trotzdem weiß, dann liegt das daran, dass hinter der URI, die wir aus Passau bekommen, keine Webseite vorhanden ist. Die Ergebnisse von Mendeley werden standartgemäß nach ganz unten gerankt. Geht man somit auf einen der unteren Ergebnisse, wird wie erwartet die Seite von Mendeley geladen.

**Comment by pstoehr** [comment]
Also das OS X Tool liefert _immer_ ein Ergebnis zurück ;-)
Auch für 
    Operation Millenium (Main Topic)
    Rhine Metropole
    Cologne
hab ich beim OS X Tool 10 von 10 Mal ein Ergebnis bekommen, im Browser hingegen bei 10 von 10 nie ein Ergebnis :-(

Vielleicht sollte man wieder explizit die Anzahl der maximalen Resultate setzen? Oder es hängt mit dem nicht übertragenen search-head zusammen ...

**Comment by lmoedl** [comment]
Gut, 10 von 10 mal bekomm ich auch kein Ergebnis 😄
Ich würde sagen, wir besprechen das morgen nochmal.
Als erste Fehlerlösung würde ich auf jeden Fall den Search-Head hinzufügen und dann kann man ja noch die Anzahl der Resultate setzen und dann nochmal testen.

**Comment by GvRecum** [comment]
Stand der Dinge?
