### ISSUE TITLE
DuckDuckGo

### ISSUE THREAD

**Issue by drui** [SECH-Tag-EEXCESS-Browser/SeCH#31]
Provider: duckduckgo

JSON Daten:
- SearchResults: Related Topics & Abstract
- title: Result & Heading
- uri: FirstURL & AbstractURL

Typ auslesen (wird noch nicht verwendet)

Erste Anzeige Abstract
"Alle Suchergebnisse" zeigt SearchResults

SearchQuery: 
http://api.duckduckgo.com/?q= +"Anfrage" + &format=json&pretty=1&t=sechbrowser

**Comment by GvRecum** [comment]
überarbeiten -> Klasse in Ordner QuerryResolution.
im Überordner liegen die Interfaces.
