### ISSUE TITLE
Ladefortschritt anzeigen bei SechInfoSeiten

### ISSUE THREAD

**Issue by bmairhoermann** [SECH-Tag-EEXCESS-Browser/SeCH#34]
Animation beim laden des Sechinhalts.

<img width="766" alt="bildschirmfoto 2016-05-10 um 14 21 18" src="https://cloud.githubusercontent.com/assets/11869474/15146259/a21759a2-16ba-11e6-8065-89f8d8d208ec.png">

@philipp92 
@Anetsch 
@bmairhoermann
@berol2

**Comment by GvRecum** [comment]
Status?

**Comment by bmairhoermann** [comment]
Noch nicht angefangen. Fraglich ob dieses Semester noch eingebaut.

**Comment by bmairhoermann** [comment]
Wurde mit einem ActivityIndicator umgesetzt. Kann eigentlich auf DONE gesetzt werden.
@GvRecum

**Comment by GvRecum** [comment]
Danke!
