### ISSUE TITLE
Faroo Rate Limit exceeded

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#44]
@lmoedl bitte Screenshot anfügen.

**Comment by lmoedl** [comment]
![screen shot 2016-05-10 at 17 21 24](https://cloud.githubusercontent.com/assets/12861122/15152122/68054a7a-16d4-11e6-8708-fe436dcbb2ca.png)

**Comment by GvRecum** [comment]
Anfragefolge zu schnell?

**Comment by GvRecum** [comment]
Wie sieht's hier aus?
Ist das behoben oder obsolet?

**Comment by pstoehr** [comment]
Hat sich, auf Grund der aktuellen Situation bei faroo, von selbst erledigt.

**Comment by lmoedl** [comment]
Der Fehler ist seitdem nicht mehr aufgetreten, aber wie Herr Stöhr schon geschrieben hat, hat sich das vorerst sowieso erledigt.
