### ISSUE TITLE
QueryResolution - DuckDuckGo

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#52]

**Comment by apoehlmann** [comment]
@drui übernimmst du das Issue oder soll ich es machen?

**Comment by drui** [comment]
da ich den rest von duckduck auch gemacht hab, kann ich das hier scho machen.
arbeite aber erst am dienstag wieder dran

**Comment by apoehlmann** [comment]
Das reicht auch vollkommen aus
