### ISSUE TITLE
QueryResolution - Faroo

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#53]

**Comment by apoehlmann** [comment]
@lmoedl übernimmst du das Issue?

**Comment by lmoedl** [comment]
Ja, übernehme ich, wenn du mir sagst, was das Problem ist

**Comment by apoehlmann** [comment]
Dein FarooConnectionCtrl muss auf die neue Struktur angepasst werden

**Comment by GvRecum** [comment]
Done oder gecancelt? @lmoedl

**Comment by lmoedl** [comment]
Das ist schon alles erledigt, wobei das aufgrund der aktuellen Situation
bei Faroo eh nicht mehr notwendig ist

Gottfried von Recum notifications@github.com schrieb am Do., 9. Juni 2016
13:26:

**Comment by GvRecum** [comment]
@lmoedl Commit "Ranking und Faroo reaktiviert"? Halten wir also an Faroo fest? @pstoehr 
Das Ranking wird Teil der WOW Version?

**Comment by lmoedl** [comment]
Ja, Faroo ist wieder online und besser als je zuvor!
Das Ranking wird alle vom Hocker hauen :stuck_out_tongue_winking_eye:
