### ISSUE TITLE
DuckDuckGo Parser stürzt ab

### ISSUE THREAD

**Issue by apoehlmann** [SECH-Tag-EEXCESS-Browser/SeCH#55]
Bei manchen Anfragen stürzt der DuckDuckGo Parser ab. Er findet einen nil Wert.
Ich hab die Stelle mit einem Kommentar markiert.

**Comment by GvRecum** [comment]
vollständig behoben? @drui

**Comment by GvRecum** [comment]
Ist der Bug vollständig beseitigt? @drui @apoehlmann 
Issues bitte nicht selbst schließen, sondern kommentieren und dann auf done setzen.

**Comment by drui** [comment]
Erst mal selbst was arbeiten. Dann kannste dich beschweren. @GvRecum 
Und wäre er nicht behoben, würde ich das hier nicht schließen.

**Comment by GvRecum** [comment]
Erstmal schön freundlich bleiben, die [Issuekonventionen](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/wiki/Issueskonventionen) beachten und immer zu den vereinbarten Treffen kommen.
Dann sieht der Fix eher nach Workaround aus, als nach vollständig behobenem Bug, sonst hätte ich das hier ja nicht geschrieben.
Ich werde es nochmal ausgiebiger testen.
Hat @apoehlmann etwas dazu?

**Comment by drui** [comment]
Der Bug ist behoben. Wurde er ein paar Tage nachdem Alex mich darauf aufmerksam gemacht hat.

**Comment by GvRecum** [comment]
Sehr gut, vielen Dank!
