### ISSUE TITLE
neue Struktur Übersicht

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#56]
Als Grundlage für die Gliederung der Doku bitte eine aktuelle Übersicht erstellen, nach Art der "Architektur(Stand 07.04.2016)" in den tmp files.
@apoehlmann macht den Content Teil, @bmairhoermann bitte den UI Teil deligieren.
Anschließend erstelle ich die Gliederung und bespreche sie mit @pstoehr.

**Comment by GvRecum** [comment]
@apoehlmann @bmairhoermann können wir das morgen einarbeiten?

**Comment by GvRecum** [comment]
@bmairhoermann Bitte die Notizen noch übertragen.

**Comment by bmairhoermann** [comment]
Gut. Aber wohin? Einfach eine Zeichnung im Dokumentenordner ablegen?

**Comment by GvRecum** [comment]
Sowie @apoehlmann (dann auch integrieren) mit [DawIO](https://www.draw.io) bitte ablegen im tmp Ordner [Architektur](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/tree/dev-may/tmp/Architektur).
Danke.

**Comment by bmairhoermann** [comment]
Done

**Comment by GvRecum** [comment]
Danke.

**Comment by GvRecum** [comment]
Liegen in [images](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/tree/dev-may/Dokumentation/images). (UI_…)
