### ISSUE TITLE
WebView lädt www.facebook.de und andere nicht.

### ISSUE THREAD

**Issue by bmairhoermann** [SECH-Tag-EEXCESS-Browser/SeCH#58]
Zur Reproduzierung:
-> gebe www.facebook.de in Adresszeile ein
-> Enter -> WebView bleibt auf aktueller Seite stehen

Andere Adresse die nicht funktionieren:
- duckduckgo.de

Vermutung:
Wenn man im Chromebrowser zum Beispiel www.facebook.de eingibt wird man auf www.facebook.COM umgeleitet. Eventuell macht das unser WebView nicht mit?

**Comment by bmairhoermann** [comment]
Habe den Fehler gefunden:

Bei Eingabe von https://facebook.de bleibt der Browser einfach stehen.

Grund:
Die Methode didFailProvisionalNavigation im WebViewDelegate ist nicht implementiert!

**Comment by GvRecum** [comment]
Status?

**Comment by bmairhoermann** [comment]
Done

**Comment by GvRecum** [comment]
Danke.
