### ISSUE TITLE
sech tabellen update

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#6]
update zeitpunkt überprüfen

**Comment by GvRecum** [comment]
Falls Abbruch nicht festgestellt werden kann, Timestamps für Resultate einühren. (Damit wir wissen, wann es erstellt wurde)

**Comment by GvRecum** [comment]
Search-Tabelle erst befüllen wenn SearchTags von EEXCESS geladen wurden.

**Comment by pwinterh** [comment]
Done
