### ISSUE TITLE
Loading Icon wird bei zweitem Aufruf nicht aktualisiert

### ISSUE THREAD

**Issue by lmoedl** [SECH-Tag-EEXCESS-Browser/SeCH#60]
Werden die Ergebnisse eines Search-Tags aus dem Cache geladen, wird das Lade-Icon nicht aktualisiert. Bei dem ersten Aufruf funktioniert der Wechsel des Icons.

**Comment by GvRecum** [comment]
Status?

**Comment by lmoedl** [comment]
Erledigt!

2016-06-20 13:01 GMT+02:00 Gottfried von Recum notifications@github.com:

**Comment by GvRecum** [comment]
Danke, dann bitte auf "Done" setzen".
