### ISSUE TITLE
Absturz des Browsers, wenn keine Daten zurückgeliefert werden bei klick auf "Alle Ergebnisse"

### ISSUE THREAD

**Issue by lmoedl** [SECH-Tag-EEXCESS-Browser/SeCH#61]
Werden keine Daten von den Suchmaschinen zurückgeliefert und es wird auf "Alle Suchergebnisse" getippt, so stürzt der Browser ab. 
Einfachster Bugfix: Button "Alle Suchergebnisse" nur enablen, wenn mehrere Suchergebnisse vorhanden

**Comment by GvRecum** [comment]
Status?

**Comment by lmoedl** [comment]
Erledigt! Button ist deaktiviert, so lange keine Daten vorhanden sind.

2016-06-20 13:01 GMT+02:00 Gottfried von Recum notifications@github.com:

**Comment by GvRecum** [comment]
Danke, dann bitte auf "Done" setzen".
