### ISSUE TITLE
Feedback an User, wenn keine Suchergebnisse vorhanden

### ISSUE THREAD

**Issue by lmoedl** [SECH-Tag-EEXCESS-Browser/SeCH#62]
Wenn keine Suchergebnisse vorhanden sind, wäre es wünschenswert, den Nutzer darauf hinzuweisen.

**Comment by GvRecum** [comment]
Gute Idee, wie ist hier der Status?

**Comment by lmoedl** [comment]
wurde mit dem Loading-Indicator gelöst.

2016-06-20 13:02 GMT+02:00 Gottfried von Recum notifications@github.com:

**Comment by GvRecum** [comment]
Danke, dann bitte auf "Done" setzen".
