### ISSUE TITLE
SEARCHModels

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#76]
Bitte die [Dokumentation](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/Dokumentation.pdf) für die [SEARCHModels](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/konstr_pro_SEARCHModels.tex) Teile verfassen.

Bitte die geänderten **[Dokumentationskonventionen](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/wiki/Dokumentationskonventionen)** beachten.

**Comment by bmairhoermann** [comment]
Done

**Comment by GvRecum** [comment]
Korrektur gelesen.
