### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#81]
Bitte die [Dokumentation](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/Dokumentation.pdf) für die [Ranking](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/konstr_pro_Ranking.tex) Teile verfassen.

Bitte die geänderten **[Dokumentationskonventionen](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/wiki/Dokumentationskonventionen)** beachten.

**Comment by GvRecum** [comment]
Korrektur gelesen.
@lmoedl ist eine mathematische Darstellung der Berechnung möglich?

**Comment by lmoedl** [comment]
Laut Herr Stöhr nicht notwendig!

**Comment by GvRecum** [comment]
Gut, war seine Anmerkung.
Also Done.
