### ISSUE TITLE
SettingsModel

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#82]
Bitte die [Dokumentation](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/Dokumentation.pdf) für die [SettingsModel](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/konstr_pro_SettingsModel.tex) Teile verfassen.

Bitte die geänderten **[Dokumentationskonventionen](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/wiki/Dokumentationskonventionen)** beachten.

**Comment by GvRecum** [comment]
Korrektur gelesen.
@drui ich habe geändert: es sind aktuell nur zwei Kategorien in den Einstellungen umgesetzt, die dritte habe ich als geplant umgeschrieben.
@pstoehr Meines Erachtens braucht das Nutzerprofil keinen Namen (anonymisierte Nutzerdaten) können wir das bitte noch rausnehmen, es ist ja eh noch nicht "wirklich" drin.

**Comment by drui** [comment]
Suchmaschineneinstellungen sind aber nicht geplant, sondern schon eingebaut.  
Also bitte nicht einfach die Doku umschreiben, wenn man nicht richtig am Projekt mitgearbeitet hat, sondern nachfragen.

**Comment by GvRecum** [comment]
Ja, diese sind im Projekt enthalten, tauchen jedoch noch nicht in den Einstellungsmöglichkeiten auf. Nichts anderes habe ich geschrieben. Da diese Änderungen alles andere als "final" sind ist das nicht "einfach umschreiben" sondern meine Aufgabe als Projektleiter.

**Comment by drui** [comment]
Ich weiß ja nicht wo du schaust, aber in der Version die ich beschrieben hatte (frisch geladen vom git) war alles so wie ich es beschrieben habe. Auch die Suchmaschinen. Nur die Startseite kann nur gesetzt werden, wird jedoch beim Start nicht beachtet.

**Comment by GvRecum** [comment]
Bei mir in einem aktuellen Build, aus dem aktuellen Git kann ich das leider nicht entdecken. Wenn das bei Dir anders aussieht würde ich mir das gerne mal ansehen.

![bildschirmfoto 2016-07-05 um 11 47 31](https://cloud.githubusercontent.com/assets/11976678/16580950/43401572-42a7-11e6-828e-477c37671a28.png)
![img_0080](https://cloud.githubusercontent.com/assets/11976678/16580951/4342f1e8-42a7-11e6-8aaa-d546862f7461.PNG)
![img_0079](https://cloud.githubusercontent.com/assets/11976678/16580949/43400f96-42a7-11e6-8c0e-ae24ed379c84.PNG)

zum Überprüfen ziehe ich mir jetzt gerne das Git erneut.
Meine Änderungen wieder zu ändern, insbesondere an der Struktur und der vorgegebenen Schreibweise der Klassen und Pakete bringt uns jedenfalls nicht weiter.

**Comment by GvRecum** [comment]
Nach einem kompletten löschen des Gits und einem neu clonen tauchen die Einstellungen, die ja vorher schon in der Klasse SettingsModel zu sehen waren, auch im Einstellungsdialog in den Geräteoptionen auf.

**Comment by GvRecum** [comment]
Die vorgegebenen Schreibweisen passe ich wieder an und bitte dies so zu lassen.

**Comment by drui** [comment]
das \lstinline hatte ich letzte woche geändert. ist nur durch deine änderung grad wohl verloren gegangen.
und wie gesagt. die einstellungen sind drin.
und meine datei is online und passt so.

**Comment by drui** [comment]
verklickt

**Comment by GvRecum** [comment]
Das Ganze geht auch ein bisschen freundlicher.
Ich passe ebenfalls die Struktur wieder an.
Dann passt es.

**Comment by drui** [comment]
Das ganze geht auch ohne Fehler in die Doku von anderen Leuten einzubauen.

**Comment by GvRecum** [comment]
Ich habe jetzt erneut Rechtschreibfehler korrigiert, die Du wieder zurück eingebaut hast und auch weitere vorgegebene Schreibweisen erneut angepasst.

**Comment by drui** [comment]
Jetzt sieht es wenigstens so aus als hättest du auch mitgearbeitet.

**Comment by GvRecum** [comment]
Ich bitte Dich erneut fair und freundlich zu bleiben.
Ratsam wäre sich nicht soweit aus dem Fenster zu lehnen, wenn man nicht überblickt, was ein Projektmanager macht und sich selbst das ganze Semester nicht sonderlich viel eingebracht hat.
