### ISSUE TITLE
Spezifikation

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#87]
Die [Dokumentation](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/Dokumentation.pdf) braucht eine [Spezifikation](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/Spezifikation.tex)

Bitte die geänderten **[Dokumentationskonventionen](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/wiki/Dokumentationskonventionen)** beachten.

**Comment by GvRecum** [comment]
Warum sind da so viele Bindestriche in den Captions? @berol2

**Comment by GvRecum** [comment]
"4. Kapitel" ?
Wenn ein Teil nur ein Kapitel hat, ist dieses nicht überflüssig?
Disskussionsvorschlag: ein zweites Kapitel hinzufügen und passende Überschriften finden, oder die Abschnitte auf Kapitelebene hochziehen. @pstoehr

**Comment by GvRecum** [comment]
Alternativvorschlag:
II. Spezifikation
4. Browser
4.1. Menüfuhrung
4.2. Lesezeichenverwaltung
4.3. Tagvervaltung
4.4. Einstellungen

**Comment by GvRecum** [comment]
Der "Admin" ist der (Be)Nutzer.

**Comment by pstoehr** [comment]
@GvRecum Kapitel 4 sieht aktuell aber ganz anders aus? Hab ich da was verpasst? 

Die \SECH und \SEARCH Makros funktionieren in den Überschriften schon, aber in einer \label-Definition nicht. Das zu fixen ist mir aktuell zu tricky

**Comment by GvRecum** [comment]
Korrektur gelesen.

**Comment by GvRecum** [comment]
Bitte noch bei Abb. 4.2 und 4.4 Search durch SeARCH ersetzen. Danke.

**Comment by ghost** [comment]
Burak sagt: GO!

**Comment by GvRecum** [comment]
Dann bitte auf Done setzen! ;)
