### ISSUE TITLE
ResponseParse

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#91]
Bitte die [Dokumentation](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/Dokumentation.pdf) für die [ResponseParse](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/blob/dev-may/Dokumentation/konstr_pro_qr_ResponseParse.tex) Teile verfassen.

Bitte die geänderten **[Dokumentationskonventionen](https://github.com/SECH-Tag-EEXCESS-Browser/SeCH/wiki/Dokumentationskonventionen)** beachten.

**Comment by GvRecum** [comment]
Korrektur gelesen.
@drui Bitte die Abb. 7.7 um 180 Grad drehen, so daß die abstrakte Klasse oben ist. Danke.

**Comment by GvRecum** [comment]
Bitte die XML dazu noch hochladen, danke.

**Comment by drui** [comment]
keine xml zum hochladen vorhanden
