### ISSUE TITLE
alle Bilder austauschen

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/SeCH#96]
@SECH-Tag-EEXCESS-Browser/team-sech 

Bitte alle .png Bilder durch .PDF Versionen ersetzen.
Bei Draw.io "Export as -> PDF -> Crop -> Export"

![bildschirmfoto_2016-06-28_um_15_58_00](https://cloud.githubusercontent.com/assets/11976678/16418425/0d1fb202-3d4a-11e6-91c9-0b444e509061.png)
![bildschirmfoto_2016-06-28_um_15_58_14](https://cloud.githubusercontent.com/assets/11976678/16418432/11764c94-3d4a-11e6-92ad-c19b6ab7bc34.png)

**Comment by GvRecum** [comment]
@apoehlmann done.
@bmairhoermann done.
@berol2 done.
@drui done.
@Anetsch done.
@lmoedl done.
gvrecum done.

**Comment by drui** [comment]
fertig
