### ISSUE TITLE
Dezent kommentierte Version der Doku ist im Repository

### ISSUE THREAD

**Issue by pstoehr** [SECH-Tag-EEXCESS-Browser/SeCH#97]
Bitte die globalen und die lokalen Anmerkungen beachten. 
Bei den "lokalen Anmerkungen": Ich hab die Sachen nur einmal angemerkt, also bitte selbständig  ähnliche Fehler fixen

**Comment by pstoehr** [comment]
Update von "DokumentationAnmerkung" in Repository

**Comment by GvRecum** [comment]
Anmerkungen eingearbeitet.
